-- 既存のテーブルが存在する場合は削除
DROP TABLE IF EXISTS transactions;

-- 取引テーブル（収入・支出の両方を管理）
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item VARCHAR NOT NULL,
    amount INTEGER NOT NULL,
    date DATE NOT NULL
);

-- インデックスの作成
CREATE INDEX idx_transactions_date ON transactions(date);

-- サンプルデータの挿入（テスト用）
INSERT INTO transactions (item, amount, date) VALUES
('給料', 250000, '2025-05-25'),
('副業収入', 50000, '2025-05-20'),
('食費', -15000, '2025-05-26'),
('光熱費', -10000, '2025-05-27');
