-- 既存のテーブルが存在する場合は削除
DROP TABLE IF EXISTS transactions;

-- 取引テーブル（収入・支出の両方を管理）
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR NOT NULL CHECK (type IN ('income', 'expense')),
    item VARCHAR NOT NULL,
    amount INTEGER NOT NULL CHECK (amount > 0),
    date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- インデックスの作成
CREATE INDEX idx_transactions_type ON transactions(type);
CREATE INDEX idx_transactions_date ON transactions(date);
CREATE INDEX idx_transactions_type_date ON transactions(type, date);

-- サンプルデータの挿入（テスト用）
INSERT INTO transactions (type, item, amount, date) VALUES
('income', '給料', 250000, '2025-05-25'),
('income', '副業収入', 50000, '2025-05-20'),
('expense', '食費', 15000, '2025-05-26'),
('expense', '光熱費', 10000, '2025-05-27');
